version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend/uploads:/app/backend/uploads
      - ../backend/results:/app/backend/results
      - ../backend/models:/app/backend/models
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
